apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test
        image: jetiba/jenkins:$BUILD_NUMBER
        ports:
        - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  labels:
   app: jenkins-test
spec:
  selector:
    app: jenkins-test
  ports:
  - protocol: "TCP"
    port: 3000
  type: LoadBalancer